overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  wrangler: 4.107.0

peerDependencyRules:
  allowedVersions:
    vite: 0.2.5

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
