import type { Provider, ProviderModel, SourceAccess, SourceFormat, SourceKind } from "./schema.ts";

export type Extractor =
  | { kind: "openai-catalog" }
  | { kind: "openai-overview" }
  | { kind: "openai-api" }
  | { kind: "openai-deprecations" }
  | { kind: "anthropic-catalog" }
  | { kind: "anthropic-api" }
  | { kind: "vercel-catalog"; minModels: number; maxModels: number }
  | { kind: "cerebras-public"; minModels: number; maxModels: number }
  | { kind: "cerebras-catalog"; minModels: number; maxModels: number }
  | { kind: "cerebras-lifecycle"; minModels: number; maxModels: number }
  | { kind: "cerebras-releases"; minModels: number; maxModels: number }
  | { kind: "cerebras-api"; minModels: number; maxModels: number }
  | { kind: "huggingface-mapping"; provider: string; minModels: number; maxModels: number }
  | { kind: "huggingface-router"; minModels: number; maxModels: number }
  | { kind: "ollama-library"; minModels: number; maxModels: number }
  | { kind: "ollama-cloud"; minModels: number; maxModels: number }
  | { kind: "bedrock-catalog" }
  | { kind: "bedrock-api" }
  | { kind: "databricks-catalog"; minModels: number; maxModels: number }
  | { kind: "databricks-api" }
  | { kind: "azure-catalog"; minModels: number; maxModels: number }
  | { kind: "azure-api" }
  | { kind: "gemini-catalog"; minModels: number; maxModels: number }
  | { kind: "gemini-api" }
  | { kind: "vertex-catalog"; minModels: number; maxModels: number }
  | { kind: "vertex-api" }
  | { kind: "cohere-catalog" }
  | { kind: "cohere-api" }
  | { kind: "mistral-catalog"; minModels: number; maxModels: number }
  | { kind: "mistral-api" }
  | { kind: "llama-catalog"; minModels: number; maxModels: number }
  | { kind: "llama-api" }
  | { kind: "xai-catalog"; minModels: number; maxModels: number }
  | { kind: "xai-api"; category: "all" | "language" | "image" | "video" }
  | {
      kind: "dashscope-catalog";
      category:
        | "text"
        | "vision"
        | "image"
        | "video"
        | "asr"
        | "tts"
        | "s2s"
        | "omni"
        | "embedding";
      minModels: number;
      maxModels: number;
    }
  | { kind: "dashscope-pricing"; minModels: number; maxModels: number }
  | { kind: "dashscope-recommended"; minModels: number; maxModels: number }
  | { kind: "dashscope-lifecycle"; minModels: number; maxModels: number }
  | { kind: "dashscope-api"; minModels: number; maxModels: number }
  | { kind: "deepseek-catalog"; minModels: number; maxModels: number }
  | { kind: "deepseek-updates"; minModels: number; maxModels: number }
  | { kind: "deepseek-api"; minModels: number; maxModels: number }
  | { kind: "kimi-openapi"; minModels: number; maxModels: number }
  | { kind: "kimi-catalog"; minModels: number; maxModels: number }
  | { kind: "kimi-pricing"; minModels: number; maxModels: number }
  | { kind: "kimi-releases"; minModels: number; maxModels: number }
  | { kind: "kimi-api"; minModels: number; maxModels: number };

export interface LinkedDocuments {
  path: RegExp;
  indexFormat?: "html" | "markdown" | "typescript";
  minDocuments: number;
  maxDocuments: number;
  concurrency: number;
  maxDocumentBytes?: number;
  pathSuffix?: ".md" | ".ts";
  documents?: {
    id: string;
    url: string;
    maxResponseBytes: number;
  }[];
}

export type SourceField =
  | "model_id"
  | "version"
  | "name"
  | "description"
  | "aliases"
  | "types"
  | "service_families"
  | "api_endpoints"
  | "routes"
  | "modalities"
  | "capabilities"
  | "limits"
  | "release_date"
  | "updated_date"
  | "pricing"
  | "availability"
  | "status"
  | "is_deprecated"
  | "deprecated_at"
  | "retired_at"
  | "replacement_model_ids";

export type CoverageField = "limits.context_tokens" | "pricing" | "release_date" | "updated_date";

export interface SourceManifest {
  id: string;
  url: string;
  type: SourceKind;
  source?: SourceKind[];
  access: SourceAccess;
  format: SourceFormat;
  stability: "documented" | "semi_structured" | "undocumented";
  extractor: Extractor;
  extractorVersion: string;
  fields: SourceField[];
  allowedHosts: string[];
  maxResponseBytes: number;
  scope?: "global" | "account" | "region" | "workspace" | "runtime";
  exhaustive?: boolean;
  role?: "catalog" | "overlay" | "inventory";
  optional?: boolean;
  auth?:
    | { scheme: "bearer"; env: string }
    | { scheme: "header"; env: string; header: string }
    | { scheme: "aws"; envs: [string, string] }
    | { scheme: "azure"; envs: [string, string, string, string, string] }
    | { scheme: "google-service-account"; env: string };
  headers?: { name: string; value: string }[];
  transport?:
    | { kind: "aws-bedrock"; region: string }
    | { kind: "databricks"; hostEnv: string }
    | { kind: "azure-models"; subscriptionEnv: string; locationEnv: string }
    | { kind: "google-model-garden"; publishers: string[] }
    | {
        kind: "ollama-cloud";
        catalogUrl: string;
        minModels: number;
        maxModels: number;
        concurrency: number;
      };
  snapshotPolicy?: "full" | "none";
  linkedDocuments?: LinkedDocuments;
}

interface ProviderManifestBase {
  provider: Omit<Provider, "source_ids" | "last_successful_sync_at" | "catalog_version">;
  supersededIdKinds?: ProviderModel["id_kind"][];
  supersededModelIds?: string[];
  warnOnMissing?: {
    sourceId: string;
    fields: CoverageField[];
    statuses?: ProviderModel["status"][];
  };
}

export type ProviderManifest = ProviderManifestBase &
  (
    | {
        sources: [...SourceManifest[], SourceManifest];
        notConfiguredReason?: undefined;
      }
    | {
        sources: [];
        notConfiguredReason: string;
      }
  );

const mebibytes = (value: number): number => value * 1024 * 1024;

const xaiApiSource = (
  id: string,
  path: string,
  category: "all" | "language" | "image" | "video",
  fields: SourceField[],
): SourceManifest => ({
  id,
  url: `https://api.x.ai/v1/${path}`,
  type: "api",
  access: "authenticated",
  format: "json",
  stability: "documented",
  extractor: { kind: "xai-api", category },
  extractorVersion: "xai-api-v1",
  fields,
  allowedHosts: ["api.x.ai"],
  maxResponseBytes: mebibytes(4),
  scope: "account",
  exhaustive: false,
  role: "inventory",
  optional: true,
  auth: { scheme: "bearer", env: "XAI_API_KEY" },
  snapshotPolicy: "none",
});

const huggingFaceInferenceSource: SourceManifest = {
  id: "huggingface-hf-inference",
  url: "https://huggingface.co/api/partners/hf-inference/models?status=live",
  type: "api",
  access: "public",
  format: "json",
  stability: "documented",
  extractor: {
    kind: "huggingface-mapping",
    provider: "hf-inference",
    minModels: 500,
    maxModels: 3_000,
  },
  extractorVersion: "huggingface-mapping-v1",
  fields: ["model_id", "routes", "types", "modalities", "status"],
  allowedHosts: ["huggingface.co"],
  maxResponseBytes: mebibytes(8),
  scope: "global",
  exhaustive: true,
  role: "catalog",
  snapshotPolicy: "none",
};

const dashscopeCatalogSource = (
  id: string,
  path: string,
  category: Extract<Extractor, { kind: "dashscope-catalog" }>["category"],
  minModels: number,
  maxModels: number,
): SourceManifest => ({
  id,
  url: `https://www.alibabacloud.com/help/en/model-studio/${path}`,
  type: "website",
  access: "public",
  format: "html",
  stability: "semi_structured",
  extractor: { kind: "dashscope-catalog", category, minModels, maxModels },
  extractorVersion: "dashscope-catalog-v1",
  fields: ["model_id", "description", "types", "modalities", "capabilities", "limits", "status"],
  allowedHosts: ["www.alibabacloud.com"],
  maxResponseBytes: mebibytes(2),
  scope: "region",
  exhaustive: false,
  role: "catalog",
});

export const manifests = [
  {
    provider: {
      id: "openai",
      name: "OpenAI",
      kind: "hosted",
      homepage: "https://openai.com/",
      docs_url: "https://developers.openai.com/api/docs/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "openai-models",
        url: "https://developers.openai.com/api/docs/models/all",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "openai-catalog" },
        extractorVersion: "openai-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "pricing",
          "status",
          "is_deprecated",
        ],
        allowedHosts: ["developers.openai.com"],
        maxResponseBytes: mebibytes(64),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^\/api\/docs\/models\/[a-z0-9._-]+$/,
          minDocuments: 80,
          maxDocuments: 140,
          concurrency: 8,
          maxDocumentBytes: mebibytes(2),
        },
      },
      {
        id: "openai-overview",
        url: "https://developers.openai.com/api/docs/models",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "openai-overview" },
        extractorVersion: "openai-overview-v1",
        fields: ["aliases"],
        allowedHosts: ["developers.openai.com"],
        maxResponseBytes: mebibytes(4),
        scope: "global",
        exhaustive: false,
        role: "overlay",
        optional: true,
      },
      {
        id: "openai-deprecations",
        url: "https://developers.openai.com/api/docs/deprecations",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "openai-deprecations" },
        extractorVersion: "openai-deprecations-v1",
        fields: ["status", "is_deprecated", "retired_at", "replacement_model_ids"],
        allowedHosts: ["developers.openai.com"],
        maxResponseBytes: mebibytes(8),
        scope: "global",
        exhaustive: true,
        role: "overlay",
        optional: true,
      },
      {
        id: "openai-api",
        url: "https://api.openai.com/v1/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "openai-api" },
        extractorVersion: "openai-api-v1",
        fields: ["model_id"],
        allowedHosts: ["api.openai.com"],
        maxResponseBytes: mebibytes(4),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "OPENAI_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "openai-models",
      fields: ["limits.context_tokens", "pricing"],
    },
  },
  {
    provider: {
      id: "anthropic",
      name: "Anthropic",
      kind: "hosted",
      homepage: "https://www.anthropic.com/",
      docs_url: "https://platform.claude.com/docs/en/about-claude/models/overview",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "anthropic-models",
        url: "https://platform.claude.com/docs/en/about-claude/models/overview.md",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "anthropic-catalog" },
        extractorVersion: "anthropic-catalog-v3",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["platform.claude.com"],
        maxResponseBytes: mebibytes(8),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^\/docs\/en\/about-claude\/(?:pricing|model-deprecations|models\/introducing-claude-fable-5-and-claude-mythos-5)$/,
          minDocuments: 3,
          maxDocuments: 3,
          concurrency: 3,
          maxDocumentBytes: mebibytes(2),
          pathSuffix: ".md",
          documents: [
            {
              id: "messages-create",
              url: "https://platform.claude.com/docs/en/api/messages/create.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "message-batches-create",
              url: "https://platform.claude.com/docs/en/api/messages/batches/create.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "batch-processing",
              url: "https://platform.claude.com/docs/en/build-with-claude/batch-processing.md",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "anthropic-api",
        url: "https://api.anthropic.com/v1/models?limit=1000",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "anthropic-api" },
        extractorVersion: "anthropic-api-v1",
        fields: ["name", "release_date", "modalities", "capabilities", "limits"],
        allowedHosts: ["api.anthropic.com"],
        maxResponseBytes: mebibytes(4),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "header", env: "ANTHROPIC_API_KEY", header: "x-api-key" },
        headers: [{ name: "anthropic-version", value: "2023-06-01" }],
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "anthropic-models",
      fields: ["limits.context_tokens", "pricing"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "amazon-bedrock",
      name: "Amazon Bedrock",
      kind: "cloud_platform",
      homepage: "https://aws.amazon.com/bedrock/",
      docs_url: "https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html",
      catalog_scope: "regional",
    },
    sources: [
      {
        id: "bedrock-models",
        url: "https://docs.aws.amazon.com/bedrock/latest/userguide/model-cards.md",
        type: "website",
        source: ["website", "api"],
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "bedrock-catalog" },
        extractorVersion: "bedrock-catalog-v4",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "availability",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
        ],
        allowedHosts: ["docs.aws.amazon.com", "pricing.us-east-1.amazonaws.com"],
        maxResponseBytes: mebibytes(32),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^\/bedrock\/latest\/userguide\/model-card-[a-z0-9-]+\.md$/,
          indexFormat: "markdown",
          minDocuments: 100,
          maxDocuments: 200,
          concurrency: 8,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "bedrock-mantle",
              url: "https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-mantle.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "pricing-bedrock",
              url: "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrock/current/index.json",
              maxResponseBytes: mebibytes(20),
            },
            {
              id: "pricing-foundation-models",
              url: "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrockFoundationModels/current/index.json",
              maxResponseBytes: mebibytes(8),
            },
            {
              id: "pricing-service",
              url: "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrockService/current/index.json",
              maxResponseBytes: mebibytes(2),
            },
          ],
        },
      },
      {
        id: "bedrock-api-us-east-1",
        url: "https://bedrock.us-east-1.amazonaws.com/foundation-models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "bedrock-api" },
        extractorVersion: "bedrock-api-v1",
        fields: [
          "name",
          "modalities",
          "capabilities",
          "release_date",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
        ],
        allowedHosts: ["bedrock.us-east-1.amazonaws.com"],
        maxResponseBytes: mebibytes(4),
        scope: "region",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: {
          scheme: "aws",
          envs: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
        },
        transport: { kind: "aws-bedrock", region: "us-east-1" },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["display_name"],
    warnOnMissing: {
      sourceId: "bedrock-models",
      fields: ["limits.context_tokens", "pricing"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "databricks",
      name: "Databricks",
      kind: "cloud_platform",
      homepage: "https://www.databricks.com/",
      docs_url:
        "https://docs.databricks.com/aws/en/machine-learning/model-serving/foundation-model-overview",
      catalog_scope: "regional",
    },
    sources: [
      {
        id: "databricks-models",
        url: "https://docs.databricks.com/aws/en/machine-learning/foundation-model-apis/supported-models",
        type: "website",
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "databricks-catalog", minModels: 40, maxModels: 80 },
        extractorVersion: "databricks-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["docs.databricks.com", "www.databricks.com"],
        maxResponseBytes: mebibytes(16),
        scope: "region",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^$/,
          indexFormat: "html",
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 4,
          documents: [
            {
              id: "overview",
              url: "https://docs.databricks.com/aws/en/machine-learning/model-serving/foundation-model-overview",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "lifecycle",
              url: "https://docs.databricks.com/aws/en/machine-learning/retired-models-policy",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "pricing-open",
              url: "https://www.databricks.com/product/pricing/foundation-model-serving",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "pricing-partner",
              url: "https://www.databricks.com/product/pricing/proprietary-foundation-model-serving",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "limits",
              url: "https://docs.databricks.com/aws/en/machine-learning/foundation-model-apis/limits",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-reference",
              url: "https://docs.databricks.com/aws/en/machine-learning/foundation-model-apis/api-reference",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "model-types",
              url: "https://docs.databricks.com/aws/en/machine-learning/model-serving/score-foundation-models",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "release-feed",
              url: "https://docs.databricks.com/aws/en/feed.xml",
              maxResponseBytes: mebibytes(2),
            },
          ],
        },
      },
      {
        id: "databricks-api",
        url: "https://workspace.cloud.databricks.com/api/2.0/serving-endpoints",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "databricks-api" },
        extractorVersion: "databricks-api-v1",
        fields: ["types", "modalities"],
        allowedHosts: ["workspace.cloud.databricks.com"],
        maxResponseBytes: mebibytes(8),
        scope: "workspace",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "DATABRICKS_TOKEN" },
        transport: { kind: "databricks", hostEnv: "DATABRICKS_HOST" },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["display_name"],
    warnOnMissing: {
      sourceId: "databricks-models",
      fields: ["limits.context_tokens", "pricing", "release_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "vercel",
      name: "Vercel AI Gateway",
      kind: "gateway",
      homepage: "https://vercel.com/ai-gateway",
      docs_url: "https://vercel.com/ai-gateway/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "vercel-models",
        url: "https://ai-gateway.vercel.sh/v1/models",
        type: "api",
        access: "public",
        format: "json",
        stability: "documented",
        extractor: { kind: "vercel-catalog", minModels: 250, maxModels: 600 },
        extractorVersion: "vercel-catalog-v3",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
        ],
        allowedHosts: ["ai-gateway.vercel.sh"],
        maxResponseBytes: mebibytes(16),
        scope: "global",
        exhaustive: true,
        role: "catalog",
      },
    ],
    warnOnMissing: {
      sourceId: "vercel-models",
      fields: ["pricing"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "azure",
      name: "Azure AI Foundry",
      kind: "cloud_platform",
      homepage: "https://azure.microsoft.com/products/ai-foundry/",
      docs_url:
        "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure",
      catalog_scope: "mixed",
    },
    sources: [
      {
        id: "azure-models",
        url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/openai/includes/models-azure-direct-openai.md",
        type: "repository",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "azure-catalog", minModels: 120, maxModels: 300 },
        extractorVersion: "azure-catalog-v2",
        fields: [
          "model_id",
          "version",
          "types",
          "service_families",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "availability",
          "status",
          "is_deprecated",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["raw.githubusercontent.com"],
        maxResponseBytes: mebibytes(8),
        scope: "global",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          path: /^$/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 7,
          documents: [
            {
              id: "direct-others",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/foundry-models/includes/models-azure-direct-others.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "partners",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/foundry-models/includes/models-partners.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "lifecycle",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/openai/includes/concepts-model-retirement-schedule-content.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "standard",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/foundry-models/includes/model-matrix/deployments-standard.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "provisioned",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/foundry-models/includes/model-matrix/deployments-provisioned.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "batch",
              url: "https://raw.githubusercontent.com/MicrosoftDocs/azure-ai-docs/main/articles/foundry/foundry-models/includes/model-matrix/deployments-batch.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "openai-v1",
              url: "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/ai/data-plane/OpenAI.v1/azure-v1-v1-generated.yaml",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "openai-v1-preview",
              url: "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/ai/data-plane/OpenAI.v1/azure-v1-preview-generated.yaml",
              maxResponseBytes: mebibytes(2),
            },
          ],
        },
      },
      {
        id: "azure-api",
        url: "https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.CognitiveServices/locations/location/models?api-version=2025-06-01",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "azure-api" },
        extractorVersion: "azure-api-v1",
        fields: [
          "model_id",
          "version",
          "description",
          "types",
          "modalities",
          "capabilities",
          "limits",
          "pricing",
          "availability",
          "status",
          "is_deprecated",
          "deprecated_at",
        ],
        allowedHosts: ["management.azure.com", "login.microsoftonline.com", "prices.azure.com"],
        maxResponseBytes: mebibytes(32),
        scope: "region",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: {
          scheme: "azure",
          envs: [
            "AZURE_TENANT_ID",
            "AZURE_CLIENT_ID",
            "AZURE_CLIENT_SECRET",
            "AZURE_SUBSCRIPTION_ID",
            "AZURE_LOCATION",
          ],
        },
        transport: {
          kind: "azure-models",
          subscriptionEnv: "AZURE_SUBSCRIPTION_ID",
          locationEnv: "AZURE_LOCATION",
        },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["display_name"],
    supersededModelIds: ["Cohere-command-a", "Mistral-medium-2505", "Mistral-small-2503"],
    warnOnMissing: {
      sourceId: "azure-models",
      fields: ["limits.context_tokens", "pricing", "release_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "gemini",
      name: "Gemini API",
      kind: "hosted",
      homepage: "https://ai.google.dev/",
      docs_url: "https://ai.google.dev/gemini-api/docs/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "gemini-models",
        url: "https://ai.google.dev/gemini-api/docs/models",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "gemini-catalog", minModels: 50, maxModels: 160 },
        extractorVersion: "gemini-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "updated_date",
          "pricing",
          "status",
          "is_deprecated",
          "retired_at",
          "replacement_model_ids",
        ],
        headers: [{ name: "Accept-Language", value: "en-US,en;q=0.9" }],
        allowedHosts: ["ai.google.dev"],
        maxResponseBytes: mebibytes(32),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^\/gemini-api\/docs\/models\/[a-z0-9.-]+$/,
          minDocuments: 30,
          maxDocuments: 60,
          concurrency: 8,
          maxDocumentBytes: mebibytes(1),
          documents: [
            {
              id: "pricing",
              url: "https://ai.google.dev/gemini-api/docs/pricing",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "deprecations",
              url: "https://ai.google.dev/gemini-api/docs/deprecations",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "changelog",
              url: "https://ai.google.dev/gemini-api/docs/changelog",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "gemma-api",
              url: "https://ai.google.dev/gemma/docs/core/gemma_on_gemini_api",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "gemma-card",
              url: "https://ai.google.dev/gemma/docs/core/model_card_4",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "interactions-overview",
              url: "https://ai.google.dev/gemini-api/docs/interactions-overview",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "interactions-api",
              url: "https://ai.google.dev/api/interactions-api",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "all-methods",
              url: "https://ai.google.dev/api/all-methods",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "live-api",
              url: "https://ai.google.dev/api/live",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "gemini-api",
        url: "https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "gemini-api" },
        extractorVersion: "gemini-api-v2",
        fields: [
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "capabilities",
          "limits",
        ],
        allowedHosts: ["generativelanguage.googleapis.com"],
        maxResponseBytes: mebibytes(8),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "header", env: "GEMINI_API_KEY", header: "x-goog-api-key" },
        snapshotPolicy: "none",
      },
    ],
    supersededModelIds: ["gemini-2.5-flash-preview-09-2025", "gemini-flash-latest"],
    warnOnMissing: {
      sourceId: "gemini-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "vertex",
      name: "Vertex AI",
      kind: "cloud_platform",
      homepage: "https://cloud.google.com/vertex-ai/",
      docs_url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models",
      catalog_scope: "regional",
    },
    sources: [
      {
        id: "vertex-google-models",
        url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/google-models",
        type: "website",
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "vertex-catalog", minModels: 25, maxModels: 90 },
        extractorVersion: "vertex-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "service_families",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "availability",
          "status",
          "is_deprecated",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["docs.cloud.google.com", "cloud.google.com"],
        headers: [{ name: "Accept-Language", value: "en-US,en;q=0.9" }],
        maxResponseBytes: mebibytes(48),
        scope: "region",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          indexFormat: "html",
          path: /^\/gemini-enterprise-agent-platform\/models\/(?:gemini\/(?!gemini-robotics-er$)|veo\/|lyria\/)[a-z0-9-]+$/,
          minDocuments: 20,
          maxDocuments: 40,
          concurrency: 8,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "lifecycle",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "imagen",
              url: "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/models/imagen/4-0-generate",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "generate-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/start",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "embedding-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/embeddings/get-multimodal-embeddings",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "image-api",
              url: "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/image/generate-images",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "video-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/video/generate-videos-from-text",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "music-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/music/generate-music",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "pricing",
              url: "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
              maxResponseBytes: mebibytes(6),
            },
          ],
        },
      },
      {
        id: "vertex-partner-models",
        url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/partner-models/use-partner-models",
        type: "website",
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "vertex-catalog", minModels: 20, maxModels: 80 },
        extractorVersion: "vertex-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "service_families",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "availability",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["docs.cloud.google.com", "cloud.google.com"],
        headers: [{ name: "Accept-Language", value: "en-US,en;q=0.9" }],
        maxResponseBytes: mebibytes(48),
        scope: "region",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          indexFormat: "html",
          path: /^\/gemini-enterprise-agent-platform\/models\/partner-models\/(?:claude\/(?!use-claude$)|grok\/(?!responses$)|mistral\/|llama\/(?!use-llama$))[a-z0-9-]+$/,
          minDocuments: 20,
          maxDocuments: 45,
          concurrency: 8,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "claude-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/partner-models/claude/use-claude",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "grok-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/partner-models/grok/responses",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "llama-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/partner-models/llama/use-llama",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "deprecations",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/deprecations/partner-models",
              maxResponseBytes: mebibytes(4),
            },
            {
              id: "pricing",
              url: "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
              maxResponseBytes: mebibytes(6),
            },
          ],
        },
      },
      {
        id: "vertex-open-models",
        url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/open-models/choose-serving-option",
        type: "website",
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "vertex-catalog", minModels: 15, maxModels: 60 },
        extractorVersion: "vertex-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "service_families",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "availability",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
        ],
        allowedHosts: ["docs.cloud.google.com", "cloud.google.com"],
        headers: [{ name: "Accept-Language", value: "en-US,en;q=0.9" }],
        maxResponseBytes: mebibytes(40),
        scope: "region",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          indexFormat: "html",
          path: /^\/gemini-enterprise-agent-platform\/models\/maas\/[a-z0-9-]+\/[a-z0-9-]+$/,
          minDocuments: 15,
          maxDocuments: 40,
          concurrency: 8,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "open-api",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/maas/call-open-model-apis",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "deprecations",
              url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/deprecations/open-models",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "pricing",
              url: "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
              maxResponseBytes: mebibytes(6),
            },
          ],
        },
      },
      {
        id: "vertex-model-garden-api",
        url: "https://aiplatform.googleapis.com/v1beta1/publishers/google/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "vertex-api" },
        extractorVersion: "vertex-api-v1",
        fields: ["model_id", "service_families", "status", "is_deprecated"],
        allowedHosts: ["aiplatform.googleapis.com", "oauth2.googleapis.com"],
        maxResponseBytes: mebibytes(32),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "google-service-account", env: "GOOGLE_SERVICE_ACCOUNT_JSON" },
        transport: {
          kind: "google-model-garden",
          publishers: [
            "google",
            "anthropic",
            "xai",
            "ai21",
            "mistralai",
            "meta",
            "deepseek-ai",
            "qwen",
            "zai-org",
            "moonshotai",
            "minimaxai",
            "openai",
          ],
        },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "vertex-google-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "cohere",
      name: "Cohere",
      kind: "hosted",
      homepage: "https://cohere.com/",
      docs_url: "https://docs.cohere.com/docs/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "cohere-models",
        url: "https://docs.cohere.com/docs/models",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "cohere-catalog" },
        extractorVersion: "cohere-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["docs.cohere.com", "cohere.com"],
        maxResponseBytes: mebibytes(48),
        scope: "global",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          path: /^\/docs\/(?:aya|aya-expanse|aya-vision|cohere-embed|command-(?:a(?:-plus|-reasoning|-translate|-vision)?|r|r-plus|r7b)|deprecations|rerank|tiny-aya|transcribe|transcribe-arabic)$/,
          minDocuments: 17,
          maxDocuments: 24,
          concurrency: 6,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "pricing",
              url: "https://cohere.com/pricing",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "changelog",
              url: "https://docs.cohere.com/v2/changelog",
              maxResponseBytes: mebibytes(3),
            },
            {
              id: "release-command-a",
              url: "https://docs.cohere.com/changelog/command-a",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "release-command-r7b",
              url: "https://docs.cohere.com/changelog/command-r-7b/",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "release-command-r",
              url: "https://docs.cohere.com/v1/changelog/command-gets-refreshed",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "release-rerank-v3-5",
              url: "https://docs.cohere.com/changelog/rerank-v3.5",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "api-chat-v2",
              url: "https://docs.cohere.com/reference/chat.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-chat-v1",
              url: "https://docs.cohere.com/reference/chat-v1.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-embed-v2",
              url: "https://docs.cohere.com/reference/embed.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-embed-jobs",
              url: "https://docs.cohere.com/reference/create-embed-job.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-rerank-v2",
              url: "https://docs.cohere.com/reference/rerank.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-transcription-v2",
              url: "https://docs.cohere.com/reference/create-audio-transcription.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-openai-compatibility",
              url: "https://docs.cohere.com/docs/compatibility-api.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "api-generate-v1",
              url: "https://docs.cohere.com/v1/reference/generate.md",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "cohere-api",
        url: "https://api.cohere.com/v1/models?page_size=1000",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "cohere-api" },
        extractorVersion: "cohere-api-v2",
        fields: ["model_id", "types", "api_endpoints", "limits", "status", "is_deprecated"],
        allowedHosts: ["api.cohere.com"],
        maxResponseBytes: mebibytes(8),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "COHERE_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["source_generated"],
    warnOnMissing: {
      sourceId: "cohere-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "mistral",
      name: "Mistral AI",
      kind: "hosted",
      homepage: "https://mistral.ai/",
      docs_url: "https://docs.mistral.ai/models/overview",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "mistral-models",
        url: "https://raw.githubusercontent.com/mistralai/platform-docs-public/main/src/schema/models/models/index.ts",
        type: "repository",
        source: ["repository", "website"],
        access: "public",
        format: "mixed",
        stability: "documented",
        extractor: { kind: "mistral-catalog", minModels: 50, maxModels: 90 },
        extractorVersion: "mistral-catalog-v2",
        fields: [
          "model_id",
          "version",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["raw.githubusercontent.com", "docs.mistral.ai"],
        maxResponseBytes: mebibytes(16),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^\/mistralai\/platform-docs-public\/main\/src\/schema\/models\/models\/[a-z0-9-]+$/,
          indexFormat: "typescript",
          pathSuffix: ".ts",
          minDocuments: 55,
          maxDocuments: 90,
          concurrency: 8,
          maxDocumentBytes: mebibytes(1),
          documents: [
            {
              id: "model-schema",
              url: "https://raw.githubusercontent.com/mistralai/platform-docs-public/main/src/schema/models/schema.ts",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "model-endpoints",
              url: "https://raw.githubusercontent.com/mistralai/platform-docs-public/main/src/schema/models/endpoints.ts",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "prompt-caching",
              url: "https://docs.mistral.ai/studio-api/conversations/advanced/prompt-caching",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "batch-processing",
              url: "https://docs.mistral.ai/studio-api/batch-processing",
              maxResponseBytes: mebibytes(4),
            },
          ],
        },
      },
      {
        id: "mistral-api",
        url: "https://api.mistral.ai/v1/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "mistral-api" },
        extractorVersion: "mistral-api-v1",
        fields: [
          "name",
          "description",
          "aliases",
          "types",
          "modalities",
          "capabilities",
          "limits",
          "status",
          "is_deprecated",
          "deprecated_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["api.mistral.ai"],
        maxResponseBytes: mebibytes(8),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "MISTRAL_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["source_generated"],
    warnOnMissing: {
      sourceId: "mistral-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "llama",
      name: "Meta Llama",
      kind: "model_publisher",
      homepage: "https://www.llama.com/",
      docs_url: "https://github.com/meta-llama/llama-models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "llama-models",
        url: "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/sku_list.py",
        type: "repository",
        access: "public",
        format: "mixed",
        stability: "documented",
        extractor: { kind: "llama-catalog", minModels: 45, maxModels: 60 },
        extractorVersion: "llama-catalog-v2",
        fields: [
          "model_id",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "pricing",
          "status",
          "is_deprecated",
        ],
        allowedHosts: ["raw.githubusercontent.com"],
        maxResponseBytes: mebibytes(12),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /^$/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 6,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "sku-types",
              url: "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/sku_types.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "prompt-guard-models",
              url: "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/cli/safety_models.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "readme",
              url: "https://raw.githubusercontent.com/meta-llama/llama-models/main/README.md",
              maxResponseBytes: mebibytes(1),
            },
            ...[
              "llama2/MODEL_CARD.md",
              "llama3/MODEL_CARD.md",
              "llama3_1/MODEL_CARD.md",
              "llama3_2/MODEL_CARD.md",
              "llama3_2/MODEL_CARD_VISION.md",
              "llama3_3/MODEL_CARD.md",
              "llama4/MODEL_CARD.md",
            ].map((path) => ({
              id: path.replaceAll("/", "-").toLowerCase(),
              url: `https://raw.githubusercontent.com/meta-llama/llama-models/main/models/${path}`,
              maxResponseBytes: mebibytes(2),
            })),
            {
              id: "llama-api-chat-example",
              url: "https://raw.githubusercontent.com/meta-llama/llama-api-python/main/examples/chat.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "llama-api-tool-example",
              url: "https://raw.githubusercontent.com/meta-llama/llama-api-python/main/examples/tool_call.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "llama-api-structured-example",
              url: "https://raw.githubusercontent.com/meta-llama/llama-api-python/main/examples/structured.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "llama-api-client",
              url: "https://raw.githubusercontent.com/meta-llama/llama-api-python/main/src/llama_api_client/_client.py",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "llama-api-chat-completions",
              url: "https://raw.githubusercontent.com/meta-llama/llama-api-python/main/src/llama_api_client/resources/chat/completions.py",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "llama-api",
        url: "https://api.llama.com/v1/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "llama-api" },
        extractorVersion: "llama-api-v1",
        fields: ["model_id", "status", "is_deprecated"],
        allowedHosts: ["api.llama.com"],
        maxResponseBytes: mebibytes(4),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "LLAMA_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    supersededIdKinds: ["display_name", "source_generated"],
    supersededModelIds: ["llama3", "llama4"],
    warnOnMissing: {
      sourceId: "llama-models",
      fields: ["release_date", "updated_date"],
      statuses: ["active"],
    },
  },
  {
    provider: {
      id: "xai",
      name: "xAI",
      kind: "hosted",
      homepage: "https://x.ai/",
      docs_url: "https://docs.x.ai/developers/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "xai-models",
        url: "https://docs.x.ai/developers/models",
        type: "website",
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "xai-catalog", minModels: 10, maxModels: 50 },
        extractorVersion: "xai-catalog-v3",
        fields: [
          "model_id",
          "name",
          "description",
          "aliases",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "release_date",
          "updated_date",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["docs.x.ai"],
        maxResponseBytes: mebibytes(8),
        scope: "global",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          path: /^$/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 1,
          documents: [
            {
              id: "llms",
              url: "https://docs.x.ai/llms.txt",
              maxResponseBytes: mebibytes(3),
            },
          ],
        },
      },
      xaiApiSource("xai-api", "models", "all", ["model_id", "aliases", "limits"]),
      xaiApiSource("xai-language-api", "language-models", "language", [
        "model_id",
        "aliases",
        "types",
        "modalities",
      ]),
      xaiApiSource("xai-image-api", "image-generation-models", "image", [
        "model_id",
        "aliases",
        "types",
        "modalities",
      ]),
      xaiApiSource("xai-video-api", "video-generation-models", "video", [
        "model_id",
        "aliases",
        "types",
        "modalities",
      ]),
    ],
    supersededIdKinds: ["display_name", "source_generated"],
    supersededModelIds: ["grok-4.20"],
    warnOnMissing: {
      sourceId: "xai-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "huggingface",
      name: "Hugging Face Inference Providers",
      kind: "gateway",
      homepage: "https://huggingface.co/",
      docs_url: "https://huggingface.co/docs/inference-providers/",
      catalog_scope: "global",
    },
    sources: [
      huggingFaceInferenceSource,
      {
        id: "huggingface-router",
        url: "https://router.huggingface.co/v1/models",
        type: "api",
        access: "public",
        format: "json",
        stability: "documented",
        extractor: { kind: "huggingface-router", minModels: 50, maxModels: 500 },
        extractorVersion: "huggingface-router-v1",
        fields: ["types", "modalities", "capabilities", "limits", "pricing"],
        allowedHosts: ["router.huggingface.co"],
        maxResponseBytes: mebibytes(16),
        scope: "global",
        exhaustive: false,
        role: "catalog",
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "huggingface-router",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "dashscope",
      name: "Alibaba Cloud Model Studio",
      kind: "cloud_platform",
      homepage: "https://www.alibabacloud.com/product/modelstudio",
      docs_url: "https://www.alibabacloud.com/help/en/model-studio/models",
      catalog_scope: "regional",
    },
    sources: [
      {
        id: "dashscope-recommended",
        url: "https://www.alibabacloud.com/help/en/model-studio/models",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "dashscope-recommended", minModels: 15, maxModels: 60 },
        extractorVersion: "dashscope-recommended-v1",
        fields: ["api_endpoints", "availability"],
        allowedHosts: ["www.alibabacloud.com"],
        maxResponseBytes: mebibytes(1),
        scope: "region",
        exhaustive: false,
        role: "overlay",
      },
      dashscopeCatalogSource("dashscope-text", "text-generation-model/", "text", 70, 180),
      dashscopeCatalogSource("dashscope-vision", "vision-model/", "vision", 12, 50),
      dashscopeCatalogSource("dashscope-image", "image-model", "image", 20, 70),
      dashscopeCatalogSource("dashscope-video", "video-generate-edit-model", "video", 25, 80),
      dashscopeCatalogSource("dashscope-asr", "asr-model/", "asr", 25, 90),
      dashscopeCatalogSource("dashscope-tts", "tts-model/", "tts", 20, 70),
      dashscopeCatalogSource("dashscope-s2s", "s2s-model", "s2s", 15, 80),
      dashscopeCatalogSource("dashscope-omni", "omni/", "omni", 20, 80),
      dashscopeCatalogSource("dashscope-embedding", "embedding-rerank-model/", "embedding", 5, 25),
      {
        id: "dashscope-pricing",
        url: "https://www.alibabacloud.com/help/en/model-studio/model-pricing",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "dashscope-pricing", minModels: 240, maxModels: 500 },
        extractorVersion: "dashscope-pricing-v1",
        fields: [
          "model_id",
          "aliases",
          "types",
          "modalities",
          "capabilities",
          "pricing",
          "availability",
          "status",
        ],
        allowedHosts: ["www.alibabacloud.com"],
        maxResponseBytes: mebibytes(2),
        scope: "region",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          path: /$a/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 1,
          documents: [
            {
              id: "context-cache",
              url: "https://www.alibabacloud.com/help/en/model-studio/context-cache",
              maxResponseBytes: mebibytes(2),
            },
          ],
        },
      },
      {
        id: "dashscope-lifecycle",
        url: "https://www.alibabacloud.com/help/en/model-studio/model-depreciation",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "dashscope-lifecycle", minModels: 15, maxModels: 150 },
        extractorVersion: "dashscope-lifecycle-v1",
        fields: [
          "model_id",
          "types",
          "status",
          "is_deprecated",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["www.alibabacloud.com"],
        maxResponseBytes: mebibytes(1),
        scope: "region",
        exhaustive: false,
        role: "catalog",
      },
      {
        id: "dashscope-deployable-api",
        url: "https://dashscope-intl.aliyuncs.com/api/v1/deployments/models?page_no=1&page_size=100&version=v1.0&model_source=base",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "dashscope-api", minModels: 1, maxModels: 100 },
        extractorVersion: "dashscope-api-v1",
        fields: ["availability"],
        allowedHosts: ["dashscope-intl.aliyuncs.com"],
        maxResponseBytes: mebibytes(2),
        scope: "region",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "DASHSCOPE_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "dashscope-pricing",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "cerebras",
      name: "Cerebras Inference",
      kind: "hosted",
      homepage: "https://www.cerebras.ai/inference",
      docs_url: "https://inference-docs.cerebras.ai/",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "cerebras-catalog",
        url: "https://inference-docs.cerebras.ai/models/overview",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "cerebras-catalog", minModels: 2, maxModels: 20 },
        extractorVersion: "cerebras-catalog-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
        ],
        allowedHosts: ["inference-docs.cerebras.ai"],
        maxResponseBytes: mebibytes(2),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          indexFormat: "markdown",
          path: /^\/models\/[a-z0-9-]+$/,
          pathSuffix: ".md",
          minDocuments: 2,
          maxDocuments: 20,
          concurrency: 6,
          maxDocumentBytes: mebibytes(1),
          documents: [
            {
              id: "prompt-caching",
              url: "https://inference-docs.cerebras.ai/capabilities/prompt-caching.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "chat-completions",
              url: "https://inference-docs.cerebras.ai/api-reference/chat-completions.md",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "completions",
              url: "https://inference-docs.cerebras.ai/api-reference/completions.md",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "cerebras-models",
        url: "https://api.cerebras.ai/public/v1/models",
        type: "api",
        access: "public",
        format: "json",
        stability: "documented",
        extractor: { kind: "cerebras-public", minModels: 2, maxModels: 20 },
        extractorVersion: "cerebras-public-v1",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "modalities",
          "capabilities",
          "limits",
          "pricing",
        ],
        allowedHosts: ["api.cerebras.ai"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: true,
        role: "catalog",
      },
      {
        id: "cerebras-lifecycle",
        url: "https://inference-docs.cerebras.ai/support/deprecation",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "cerebras-lifecycle", minModels: 10, maxModels: 30 },
        extractorVersion: "cerebras-lifecycle-v1",
        fields: [
          "model_id",
          "types",
          "modalities",
          "status",
          "is_deprecated",
          "deprecated_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["inference-docs.cerebras.ai"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: false,
        role: "catalog",
      },
      {
        id: "cerebras-releases",
        url: "https://inference-docs.cerebras.ai/support/change-log",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "cerebras-releases", minModels: 10, maxModels: 30 },
        extractorVersion: "cerebras-releases-v1",
        fields: ["release_date"],
        allowedHosts: ["inference-docs.cerebras.ai"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: false,
        role: "overlay",
      },
      {
        id: "cerebras-api",
        url: "https://api.cerebras.ai/v1/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "cerebras-api", minModels: 1, maxModels: 20 },
        extractorVersion: "cerebras-api-v1",
        fields: ["model_id"],
        allowedHosts: ["api.cerebras.ai"],
        maxResponseBytes: mebibytes(1),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "CEREBRAS_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "cerebras-models",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "ollama",
      name: "Ollama",
      kind: "local_runtime",
      homepage: "https://ollama.com/",
      docs_url: "https://docs.ollama.com/cloud",
      catalog_scope: "mixed",
    },
    sources: [
      {
        id: "ollama-library",
        url: "https://ollama.com/library",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "ollama-library", minModels: 200, maxModels: 350 },
        extractorVersion: "ollama-library-v2",
        fields: [
          "model_id",
          "description",
          "types",
          "service_families",
          "modalities",
          "capabilities",
          "updated_date",
          "pricing",
          "status",
        ],
        allowedHosts: ["ollama.com"],
        maxResponseBytes: mebibytes(4),
        scope: "global",
        exhaustive: false,
        role: "catalog",
      },
      {
        id: "ollama-cloud-models",
        url: "https://ollama.com/api/tags",
        type: "api",
        source: ["api", "website"],
        access: "public",
        format: "mixed",
        stability: "semi_structured",
        extractor: { kind: "ollama-cloud", minModels: 15, maxModels: 30 },
        extractorVersion: "ollama-cloud-v2",
        fields: [
          "model_id",
          "name",
          "description",
          "types",
          "service_families",
          "modalities",
          "capabilities",
          "limits",
          "updated_date",
          "pricing",
          "status",
          "is_deprecated",
          "retired_at",
        ],
        allowedHosts: ["ollama.com"],
        maxResponseBytes: mebibytes(4),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        transport: {
          kind: "ollama-cloud",
          catalogUrl: "https://ollama.com/search?c=cloud",
          minModels: 15,
          maxModels: 30,
          concurrency: 6,
        },
      },
    ],
    warnOnMissing: {
      sourceId: "ollama-library",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated"],
    },
  },
  {
    provider: {
      id: "vllm",
      name: "vLLM runtime",
      kind: "local_runtime",
      homepage: "https://vllm.ai/",
      docs_url: "https://docs.vllm.ai/en/latest/serving/online_serving/openai_compatible_server/",
      catalog_scope: "runtime",
    },
    sources: [],
    notConfiguredReason: "No explicitly allowlisted runtime endpoint is configured.",
  },
  {
    provider: {
      id: "deepseek",
      name: "DeepSeek",
      kind: "hosted",
      homepage: "https://www.deepseek.com/",
      docs_url: "https://api-docs.deepseek.com/api/list-models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "deepseek-catalog",
        url: "https://api-docs.deepseek.com/quick_start/pricing",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "deepseek-catalog", minModels: 4, maxModels: 10 },
        extractorVersion: "deepseek-catalog-v2",
        fields: [
          "model_id",
          "name",
          "types",
          "api_endpoints",
          "modalities",
          "capabilities",
          "limits",
          "pricing",
          "status",
          "is_deprecated",
          "deprecated_at",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["api-docs.deepseek.com"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: true,
        role: "catalog",
        linkedDocuments: {
          path: /$a/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 1,
          documents: [
            {
              id: "chat-completions",
              url: "https://api-docs.deepseek.com/api/create-chat-completion",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "deepseek-updates",
        url: "https://api-docs.deepseek.com/updates",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "deepseek-updates", minModels: 4, maxModels: 10 },
        extractorVersion: "deepseek-updates-v1",
        fields: ["release_date", "updated_date"],
        allowedHosts: ["api-docs.deepseek.com"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: false,
        role: "overlay",
      },
      {
        id: "deepseek-api",
        url: "https://api.deepseek.com/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "deepseek-api", minModels: 1, maxModels: 20 },
        extractorVersion: "deepseek-api-v1",
        fields: ["model_id"],
        allowedHosts: ["api.deepseek.com"],
        maxResponseBytes: mebibytes(1),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "DEEPSEEK_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "deepseek-catalog",
      fields: ["release_date", "updated_date"],
      statuses: ["active", "deprecated"],
    },
  },
  {
    provider: {
      id: "kimi",
      name: "Kimi",
      kind: "hosted",
      homepage: "https://www.kimi.com/",
      docs_url: "https://platform.kimi.com/docs/models",
      catalog_scope: "global",
    },
    sources: [
      {
        id: "kimi-openapi",
        url: "https://platform.kimi.com/docs/openapi.json",
        type: "website",
        access: "public",
        format: "json",
        stability: "documented",
        extractor: { kind: "kimi-openapi", minModels: 8, maxModels: 30 },
        extractorVersion: "kimi-openapi-v2",
        fields: ["model_id", "types", "modalities", "api_endpoints", "capabilities"],
        allowedHosts: ["platform.kimi.com"],
        maxResponseBytes: mebibytes(2),
        scope: "global",
        exhaustive: false,
        role: "catalog",
      },
      {
        id: "kimi-catalog",
        url: "https://platform.kimi.com/docs/models",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "kimi-catalog", minModels: 15, maxModels: 30 },
        extractorVersion: "kimi-catalog-v1",
        fields: [
          "model_id",
          "description",
          "types",
          "modalities",
          "capabilities",
          "limits",
          "status",
          "is_deprecated",
          "retired_at",
          "replacement_model_ids",
        ],
        allowedHosts: ["platform.kimi.com"],
        maxResponseBytes: mebibytes(1),
        scope: "global",
        exhaustive: false,
        role: "catalog",
      },
      {
        id: "kimi-pricing",
        url: "https://platform.kimi.com/docs/pricing/chat-k3",
        type: "website",
        access: "public",
        format: "markdown",
        stability: "semi_structured",
        extractor: { kind: "kimi-pricing", minModels: 8, maxModels: 20 },
        extractorVersion: "kimi-pricing-v1",
        fields: ["model_id", "name", "types", "modalities", "capabilities", "limits", "pricing"],
        allowedHosts: ["platform.kimi.com"],
        maxResponseBytes: mebibytes(8),
        scope: "global",
        exhaustive: false,
        role: "catalog",
        linkedDocuments: {
          indexFormat: "markdown",
          path: /^$/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 6,
          maxDocumentBytes: mebibytes(1),
          documents: [
            {
              id: "k27",
              url: "https://platform.kimi.com/docs/pricing/chat-k27-code",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "k26",
              url: "https://platform.kimi.com/docs/pricing/chat-k26",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "k25",
              url: "https://platform.kimi.com/docs/pricing/chat-k25",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "v1",
              url: "https://platform.kimi.com/docs/pricing/chat-v1",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "batch",
              url: "https://platform.kimi.com/docs/pricing/batch",
              maxResponseBytes: mebibytes(1),
            },
            {
              id: "cache",
              url: "https://platform.kimi.com/docs/guide/use-context-caching-feature-of-kimi-api",
              maxResponseBytes: mebibytes(1),
            },
          ],
        },
      },
      {
        id: "kimi-releases",
        url: "https://platform.kimi.com/blog/posts/changelog",
        type: "website",
        access: "public",
        format: "html",
        stability: "semi_structured",
        extractor: { kind: "kimi-releases", minModels: 8, maxModels: 25 },
        extractorVersion: "kimi-releases-v1",
        fields: ["release_date"],
        allowedHosts: ["platform.kimi.com", "www.kimi.com"],
        maxResponseBytes: mebibytes(6),
        scope: "global",
        exhaustive: false,
        role: "overlay",
        linkedDocuments: {
          indexFormat: "html",
          path: /^$/,
          minDocuments: 0,
          maxDocuments: 0,
          concurrency: 2,
          maxDocumentBytes: mebibytes(2),
          documents: [
            {
              id: "research",
              url: "https://www.kimi.com/blog/",
              maxResponseBytes: mebibytes(2),
            },
            {
              id: "code",
              url: "https://www.kimi.com/code/docs/en/kimi-code/whats-new.html",
              maxResponseBytes: mebibytes(2),
            },
          ],
        },
      },
      {
        id: "kimi-api",
        url: "https://api.moonshot.ai/v1/models",
        type: "api",
        access: "authenticated",
        format: "json",
        stability: "documented",
        extractor: { kind: "kimi-api", minModels: 1, maxModels: 50 },
        extractorVersion: "kimi-api-v1",
        fields: ["model_id", "modalities", "capabilities", "limits"],
        allowedHosts: ["api.moonshot.ai"],
        maxResponseBytes: mebibytes(1),
        scope: "account",
        exhaustive: false,
        role: "inventory",
        optional: true,
        auth: { scheme: "bearer", env: "MOONSHOT_API_KEY" },
        snapshotPolicy: "none",
      },
    ],
    warnOnMissing: {
      sourceId: "kimi-catalog",
      fields: ["limits.context_tokens", "pricing", "release_date", "updated_date"],
      statuses: ["active", "preview", "deprecated", "unknown"],
    },
  },
] satisfies ProviderManifest[];
