export const standardPriceDimensions = [
  "model",
  "region",
  "endpoint",
  "deployment_type",
  "deployment_scope",
  "service_tier",
  "speed",
  "inference_geo",
  "route_provider",
  "context_tier",
  "modality",
  "operation",
  "resolution",
  "quality",
  "style",
  "capacity",
  "billing_period",
  "account_eligibility",
  "request_audio",
  "voice_control",
  "video_input",
  "promotion",
  "cache_ttl_seconds",
  "context_tokens",
  "input_tokens",
  "output_tokens",
  "duration_seconds",
] as const;

export const standardBillingUnits = [
  "token",
  "character",
  "byte",
  "pixel",
  "image",
  "page",
  "request",
  "second",
  "month",
  "frame",
  "video",
  "audio",
  "instance",
  "gpu",
] as const;

export const standardPriceMeters = [
  "input_text",
  "output_text",
  "cache_read_text",
  "cache_write_text",
  "cache_read_audio",
  "cache_write_audio",
  "cache_read_image",
  "cache_write_image",
  "cache_read_video",
  "cache_write_video",
  "cache_storage",
  "input_audio",
  "output_audio",
  "input_image",
  "output_image",
  "input_video",
  "output_video",
  "image_generation",
  "video_generation",
  "embedding",
  "rerank_request",
  "tool_call",
  "realtime_client_message",
  "realtime_session_duration",
  "gpu_hour",
  "provisioned_throughput",
  "batch_inference",
] as const;

export const publishedTimePrecisions = ["year", "month", "date", "datetime"] as const;
export const pricingRefreshFailureCodes = [
  "source_unavailable",
  "source_schema_changed",
  "pricing_validation_failed",
  "provider_refresh_failed",
  "pricing_not_observed",
] as const;
export const priceStates = ["numeric", "free", "custom_quote", "not_published"] as const;
export const rawPricingImpacts = ["base_price", "allowance", "informational"] as const;
