export const standardPriceDimensions = [
  "model",
  "region",
  "endpoint",
  "deployment_type",
  "deployment_scope",
  "service_tier",
  "requested_service_tier",
  "served_service_tier",
  "speed",
  "inference_geo",
  "route_provider",
  "context_tier",
  "modality",
  "operation",
  "resolution",
  "quality",
  "style",
  "capacity",
  "billing_period",
  "billing_currency",
  "account_eligibility",
  "request_audio",
  "voice_control",
  "video_input",
  "promotion",
  "cache_ttl_seconds",
  "context_tokens",
  "input_tokens",
  "output_tokens",
  "duration_seconds",
] as const;

export const standardBillingUnits = [
  "token",
  "character",
  "byte",
  "pixel",
  "request",
  "event",
  "item",
  "image",
  "page",
  "frame",
  "second",
  "billing_day",
  "billing_month",
  "billing_year",
  "seat",
  "instance",
  "replica",
  "accelerator",
  "capacity_unit",
] as const;

export const standardPriceMeters = [
  "input_text",
  "output_text",
  "cache_read_text",
  "cache_write_text",
  "input_audio",
  "output_audio",
  "input_image",
  "output_image",
  "input_video",
  "output_video",
  "image_generation",
  "video_generation",
  "embedding",
  "rerank",
  "transcription",
  "speech_generation",
  "web_search",
  "image_search",
  "maps_search",
  "file_search",
  "retrieval",
  "grounded_generation",
  "code_execution",
  "container_runtime",
  "session_runtime",
  "storage",
  "data_transfer",
  "content_safety",
  "custom_reporting",
  "training_input",
  "training_compute",
  "evaluation",
  "compute",
  "provisioned_capacity",
  "subscription",
  "acquisition",
] as const;

export const standardUsageSignals = [
  "input_tokens",
  "uncached_input_tokens",
  "cached_input_tokens",
  "cache_write_tokens",
  "output_tokens",
  "accepted_requests",
  "completed_result_items",
  "successful_web_searches",
  "generated_items",
  "generated_images",
  "generated_seconds",
  "active_seconds",
  "stored_byte_seconds",
  "transferred_bytes",
] as const;

export const applicabilityResolutionPhases = [
  "publication",
  "request",
  "outcome",
  "account",
] as const;

export const standardResourceKinds = [
  "service",
  "plan",
  "capacity",
  "distribution",
  "account_resource_template",
] as const;

export const publishedTimePrecisions = ["year", "month", "date", "datetime"] as const;
export const pricingRefreshFailureCodes = [
  "source_unavailable",
  "source_schema_changed",
  "pricing_validation_failed",
  "provider_refresh_failed",
  "pricing_not_observed",
] as const;
export const priceStates = [
  "numeric",
  "free",
  "included",
  "externally_billed",
  "custom_quote",
  "not_published",
] as const;
export const enrollmentStates = [
  "open",
  "waitlist",
  "closed_to_new",
  "private_preview",
  "account_scoped",
] as const;
export const rawPricingImpacts = ["base_price", "allowance", "informational"] as const;
